import { MenuItem } from '@/types/menu';

export const menuItemsReal: MenuItem[] = [
  // ENTRADAS
  {
    id: 'ent-001',
    nombre: 'Pan de Ajo Gratinado',
    categoria: 'entradas',
    precio: 100,
    descripcion: 'Pan tostado con un toque de mantequilla con ajo y mezcla de quesos',
    tiempoPrep: 10,
  },
  {
    id: 'ent-002',
    nombre: 'Champiñones al Ajillo',
    categoria: 'entradas',
    precio: 120,
    descripcion: 'Champiñón sarteneado con salsa al ajillo de la casa',
    tiempoPrep: 12,
  },
  {
    id: 'ent-003',
    nombre: 'Champiñones al Forno',
    categoria: 'entradas',
    precio: 130,
    descripcion: 'Champiñón horneado gratinado con láminas de queso parmesano',
    tiempoPrep: 15,
  },
  {
    id: 'ent-004',
    nombre: 'Espárragos a la Parmesana',
    categoria: 'entradas',
    precio: 140,
    descripcion: 'Espárragos horneados con un toque de parmesano GRANA PADANO',
    tiempoPrep: 12,
  },
  {
    id: 'ent-005',
    nombre: 'Aceitunas',
    categoria: 'entradas',
    precio: 160,
    descripcion: 'Blue Cheese, Pimientos y Anchoas',
    tiempoPrep: 5,
  },
  {
    id: 'ent-006',
    nombre: 'Queso Frito',
    categoria: 'entradas',
    precio: 170,
    descripcion: 'Queso Mozzarella fresco empanizado con pan de la casa con una salsa Pomodoro',
    tiempoPrep: 15,
  },
  {
    id: 'ent-007',
    nombre: 'Carpaccio de Portobello',
    categoria: 'entradas',
    precio: 170,
    descripcion: 'Finas láminas de Portobello, bañados con una salsa negra, aceite de oliva y arúgula fresca',
    tiempoPrep: 10,
  },
  {
    id: 'ent-008',
    nombre: 'Carpaccio de Atún',
    categoria: 'entradas',
    precio: 180,
    descripcion: 'Láminas de Atún, bañados con una salsa Ponzu cítrica con rodajas de jalapeño',
    tiempoPrep: 10,
    proteina: ['pescado'],
    picante: true,
    destacado: true,
  },
  {
    id: 'ent-009',
    nombre: 'Prosciutto',
    nombreItalia: 'Prosciutto di Parma',
    categoria: 'entradas',
    precio: 180,
    descripcion: '100grs. De Prosciutto finamente laminado en mesa, acompañado con pan tomate - Preparada en mesa',
    tiempoPrep: 8,
    proteina: ['cerdo'],
    destacado: true,
  },
  {
    id: 'ent-010',
    nombre: 'Portobello Gratinado',
    categoria: 'entradas',
    precio: 180,
    descripcion: 'Portobello horneado, gratinado a 3 quesos Mozzarella, Gouda y Parmesano, acompañados con verduras',
    tiempoPrep: 18,
  },
  {
    id: 'ent-011',
    nombre: 'Tartar de Atún',
    categoria: 'entradas',
    precio: 180,
    descripcion: 'Atún fresco en cubos con un toque de aguacate y una salsa Ponzu',
    tiempoPrep: 12,
    proteina: ['pescado'],
  },
  {
    id: 'ent-012',
    nombre: 'Formaggio',
    categoria: 'entradas',
    precio: 180,
    descripcion: 'Es una mezcla de 4 quesos con espinaca, Jitomate Cherry horneado, acompañado de pan de la casa',
    tiempoPrep: 15,
  },
  {
    id: 'ent-013',
    nombre: 'Hamburguesa de Portobello',
    categoria: 'entradas',
    precio: 200,
    descripcion: '200 grs. de carne de Res Choice, Portobello horneado gratinado con un toque de mostaza de Dijon',
    tiempoPrep: 20,
    proteina: ['res'],
  },
  {
    id: 'ent-014',
    nombre: 'Carpaccio Di Manzo',
    nombreItalia: 'Carpaccio di Manzo',
    categoria: 'entradas',
    precio: 210,
    descripcion: 'Finas láminas de filete de lomo de Res con un toque de parmesano Arúgula fresca y aceite de oliva a las finas hierbas y alcaparras',
    tiempoPrep: 12,
    proteina: ['res'],
  },
  {
    id: 'ent-015',
    nombre: 'Carpaccio de Salmón',
    categoria: 'entradas',
    precio: 210,
    descripcion: 'Salmón fresco en corte de Sashimi bañado en salsa',
    tiempoPrep: 10,
    proteina: ['pescado'],
  },
  {
    id: 'ent-016',
    nombre: 'Pulpo Bañado',
    categoria: 'entradas',
    precio: 230,
    descripcion: 'Pulpo bañado, harinado, crocante con una salsa estilo Arrabiata con queso Grana Padano',
    tiempoPrep: 18,
    proteina: ['mariscos'],
    picante: true,
  },
  {
    id: 'ent-017',
    nombre: 'Calamares Fritos',
    nombreItalia: 'Calamari Fritti',
    categoria: 'entradas',
    precio: 240,
    descripcion: 'Harinado, crocante con parmesano y toque de tártara',
    tiempoPrep: 20,
    proteina: ['mariscos'],
  },
  {
    id: 'ent-018',
    nombre: 'Tabla de Quesos',
    categoria: 'entradas',
    subcategoria: 'tabla',
    precio: 310,
    descripcion: 'Queso Gouda, Queso Mozzarella, Blue Cheese, Queso de Cabra Cenizo, Queso Clásico Parmesano y Queso de Rancho de los Altos',
    tiempoPrep: 8,
  },
  {
    id: 'ent-019',
    nombre: 'Tapas de Rib Eye',
    categoria: 'entradas',
    precio: 315,
    descripcion: 'Chicharrón de Rib Eye, con Pan Pita con un toque de guacamole, coronado con cebolla y cilantro',
    tiempoPrep: 15,
    proteina: ['res'],
  },

  // PROTEINAS - BELLARYA IN CASA
  {
    id: 'pro-001',
    nombre: 'Lasaña Di Manzo',
    nombreItalia: 'Lasagne di Manzo',
    categoria: 'proteinas',
    subcategoria: 'bellarya in casa',
    precio: 180,
    descripcion: 'Pasta Lasaña con salsa tradicional de la casa, carne de res con una mezcla de quesos de la casa',
    tiempoPrep: 25,
    proteina: ['res'],
  },
  {
    id: 'pro-002',
    nombre: 'Lasaña de Camarón',
    categoria: 'proteinas',
    subcategoria: 'bellarya in casa',
    precio: 200,
    descripcion: 'Pasta Lasaña, una salsa clásica bechamel, Camarones a la mantequilla, pimientos y nuestra gran mezcla de quesos',
    tiempoPrep: 25,
    proteina: ['mariscos'],
  },
  {
    id: 'pro-003',
    nombre: "Filete al All'Asino",
    categoria: 'proteinas',
    subcategoria: 'bellarya in casa',
    precio: 320,
    descripcion: 'Filete lomo de Res con una mantequilla de la casa',
    tiempoPrep: 22,
    proteina: ['res'],
  },
  {
    id: 'pro-004',
    nombre: 'Rib Eye a las Finas Hierbas',
    categoria: 'proteinas',
    subcategoria: 'bellarya in casa',
    precio: 360,
    descripcion: '400 gramos de Rib Eye a las finas hierbas',
    tiempoPrep: 20,
    proteina: ['res'],
    destacado: true,
  },
  {
    id: 'pro-005',
    nombre: 'Rib Eye a las Finas Hierbas',
    categoria: 'proteinas',
    subcategoria: 'bellarya in casa',
    precio: 520,
    descripcion: '600 gramos de Rib Eye a las finas hierbas',
    tiempoPrep: 20,
    proteina: ['res'],
  },
  {
    id: 'pro-006',
    nombre: 'Tacos de Langosta',
    categoria: 'proteinas',
    subcategoria: 'bellarya in casa',
    precio: 900,
    descripcion: 'Tortilla de lechuga romana, Cola de langosta acompañada con mantequilla clarificada y salsa de la casa',
    tiempoPrep: 20,
    proteina: ['mariscos'],
  },
  {
    id: 'pro-007',
    nombre: 'Tomahawk Bellarya',
    categoria: 'proteinas',
    subcategoria: 'bellarya in casa',
    precio: 1100,
    descripcion: '1kg de Tomahawk a las finas hierbas y un toque de sal',
    tiempoPrep: 40,
    proteina: ['res'],
    destacado: true,
  },
  {
    id: 'pro-008',
    nombre: 'Cola de Langosta Bellarya',
    categoria: 'proteinas',
    subcategoria: 'bellarya in casa',
    precio: 2100,
    descripcion: 'Langosta a la mantequilla con cítricos',
    tiempoPrep: 40,
    proteina: ['mariscos'],
  },

  // PROTEINAS - PESCADOS
  {
    id: 'pro-009',
    nombre: 'Pescado a la Nonna',
    categoria: 'proteinas',
    subcategoria: 'pescados',
    precio: 300,
    descripcion: 'Pescado adobado con salsa de 7 chiles de la casa',
    tiempoPrep: 22,
    proteina: ['pescado'],
    picante: true,
  },
  {
    id: 'pro-010',
    nombre: 'Pescado al Chipotle',
    categoria: 'proteinas',
    subcategoria: 'pescados',
    precio: 300,
    descripcion: 'Pescado con salsa cremosa de chipotle con un toque de mantequilla',
    tiempoPrep: 22,
    proteina: ['pescado'],
    picante: true,
  },
  {
    id: 'pro-011',
    nombre: 'Pescado a la Florentina',
    categoria: 'proteinas',
    subcategoria: 'pescados',
    precio: 310,
    descripcion: 'Pescado al grill a las finas hierbas con mezcla de lechugas y bastones de verdura',
    tiempoPrep: 20,
    proteina: ['pescado'],
  },
  {
    id: 'pro-012',
    nombre: 'Pescado a la Mantequilla',
    categoria: 'proteinas',
    subcategoria: 'pescados',
    precio: 320,
    descripcion: 'Pescado con una mantequilla compuesta a base de romero, perejil, pimienta y limón',
    tiempoPrep: 20,
    proteina: ['pescado'],
  },
  {
    id: 'pro-013',
    nombre: 'Pescado a la Sal',
    categoria: 'proteinas',
    subcategoria: 'pescados',
    precio: 600,
    descripcion: 'Preparada en mesa - A las finas hierbas horneado en capa de sal',
    tiempoPrep: 40,
    proteina: ['pescado'],
  },

  // PROTEINAS - POLLO
  {
    id: 'pro-014',
    nombre: 'Pollo en Salsa de Queso',
    categoria: 'proteinas',
    subcategoria: 'pollo',
    precio: 230,
    descripcion: 'Pollo en salsa con una mezcla de quesos de la casa',
    tiempoPrep: 20,
    proteina: ['pollo'],
  },
  {
    id: 'pro-015',
    nombre: 'Pollo a la Napolitana',
    categoria: 'proteinas',
    subcategoria: 'pollo',
    precio: 230,
    descripcion: 'Pollo empanizado con pan toscano con salsa pomodoro y queso mozzarella fresco',
    tiempoPrep: 20,
    proteina: ['pollo'],
  },
  {
    id: 'pro-016',
    nombre: 'Pollo Arrabiata',
    categoria: 'proteinas',
    subcategoria: 'pollo',
    precio: 230,
    descripcion: 'Pechuga de Pollo bañado de salsa picante con pomodoro y un toque de peperoncino',
    tiempoPrep: 20,
    proteina: ['pollo'],
    picante: true,
  },
  {
    id: 'pro-017',
    nombre: 'Pollo Tropical',
    categoria: 'proteinas',
    subcategoria: 'pollo',
    precio: 240,
    descripcion: 'Pechuga de Pollo horneada y sarteneada acompañada de mix de pimiento gratinado y un toque de tocino',
    tiempoPrep: 25,
    proteina: ['pollo', 'cerdo'],
  },

  // PROTEINAS - SALMÓN
  {
    id: 'pro-018',
    nombre: 'Salmón a las Finas Hierbas',
    categoria: 'proteinas',
    subcategoria: 'salmón',
    precio: 280,
    descripcion: 'Salmón horneado a las finas hierbas y un toque de mantequilla clarificada',
    tiempoPrep: 20,
    proteina: ['pescado'],
  },
  {
    id: 'pro-019',
    nombre: 'Salmón Nonna',
    categoria: 'proteinas',
    subcategoria: 'salmón',
    precio: 280,
    descripcion: 'Salmón adobado con salsa de la casa de 7 chiles',
    tiempoPrep: 20,
    proteina: ['pescado'],
    picante: true,
  },
  {
    id: 'pro-020',
    nombre: 'Salmón Tropical',
    categoria: 'proteinas',
    subcategoria: 'salmón',
    precio: 280,
    descripcion: 'Salmón horneado con mix de pimientos gratinados y un toque de tocino',
    tiempoPrep: 25,
    proteina: ['pescado', 'cerdo'],
  },
  {
    id: 'pro-021',
    nombre: 'Salmón Bellarya',
    categoria: 'proteinas',
    subcategoria: 'salmón',
    precio: 290,
    descripcion: 'Salmón horneado con finas hierbas en una cama de verduras y bastones de verdura',
    tiempoPrep: 22,
    proteina: ['pescado'],
  },

  // PROTEINAS - PULPO
  {
    id: 'pro-022',
    nombre: 'Pulpo Nonna',
    categoria: 'proteinas',
    subcategoria: 'pulpo',
    precio: 300,
    descripcion: 'Pulpo adobado con la salsa de casa de 7 chiles',
    tiempoPrep: 20,
    proteina: ['mariscos'],
    picante: true,
  },
  {
    id: 'pro-023',
    nombre: 'Pulpo Ajillo',
    categoria: 'proteinas',
    subcategoria: 'pulpo',
    precio: 300,
    descripcion: 'Pulpo adobado con el mero sabor al ajillo',
    tiempoPrep: 20,
    proteina: ['mariscos'],
  },
  {
    id: 'pro-024',
    nombre: 'Pulpo Matricciata',
    categoria: 'proteinas',
    subcategoria: 'pulpo',
    precio: 300,
    descripcion: 'Pulpo bañado en vino blanco con un toque de picante y salsa Arrabiata',
    tiempoPrep: 30,
    proteina: ['mariscos'],
    picante: true,
  },
  {
    id: 'pro-025',
    nombre: 'Pulpo a la Pratto',
    categoria: 'proteinas',
    subcategoria: 'pulpo',
    precio: 310,
    descripcion: 'Pulpo, camarón y marlín ahumado picado con cebolla y serrano',
    tiempoPrep: 20,
    proteina: ['mariscos'],
    picante: true,
  },

  // PROTEINAS - CAMARONES
  {
    id: 'pro-026',
    nombre: 'Camarones',
    categoria: 'proteinas',
    subcategoria: 'camarones',
    precio: 270,
    descripcion: 'A la Diabla, Mantequilla o Al Mojo (a elegir)',
    tiempoPrep: 18,
    proteina: ['mariscos'],
  },
  {
    id: 'pro-027',
    nombre: "Camarones All'Asino",
    categoria: 'proteinas',
    subcategoria: 'camarones',
    precio: 270,
    descripcion: 'Camarones bañados de mantequilla, compuesta a base de romero, perejil, pimienta, sal y limón',
    tiempoPrep: 18,
    proteina: ['mariscos'],
  },
  {
    id: 'pro-028',
    nombre: 'Gambas Cremosas',
    categoria: 'proteinas',
    subcategoria: 'camarones',
    precio: 270,
    descripcion: 'Camarones con cabeza, con una mayonesa compuesta a base de chiles en un espejo de lechugas',
    tiempoPrep: 18,
    proteina: ['mariscos'],
    picante: true,
  },
  {
    id: 'pro-029',
    nombre: 'Camarones a la Nonna',
    categoria: 'proteinas',
    subcategoria: 'camarones',
    precio: 280,
    descripcion: 'Camarones con una salsa de 7 chiles de la casa con un toque de aceite de oliva',
    tiempoPrep: 18,
    proteina: ['mariscos'],
    picante: true,
  },
  {
    id: 'pro-030',
    nombre: 'Camarón Diávolo',
    categoria: 'proteinas',
    subcategoria: 'camarones',
    precio: 280,
    descripcion: 'Camarón picante cremoso con espárragos',
    tiempoPrep: 18,
    proteina: ['mariscos'],
    picante: true,
  },
  {
    id: 'pro-031',
    nombre: 'Camarón Toscano',
    categoria: 'proteinas',
    subcategoria: 'camarones',
    precio: 290,
    descripcion: 'Sobre un pan toscano camarón cremoso con peperoncino y jitomate Cherry, espolvoreado de perejil',
    tiempoPrep: 18,
    proteina: ['mariscos'],
    picante: true,
  },
  {
    id: 'pro-032',
    nombre: 'Langostino Bellarya',
    categoria: 'proteinas',
    subcategoria: 'camarones',
    precio: 350,
    descripcion: 'Langostino adobado con un adobo de salsas de 6 chiles con aderezo de mostaza y miel',
    tiempoPrep: 20,
    proteina: ['mariscos'],
    picante: true,
  },

  // PROTEINAS - MEJILLONES
  {
    id: 'pro-033',
    nombre: 'Mejillón al Vino Blanco',
    categoria: 'proteinas',
    subcategoria: 'mejillones',
    precio: 240,
    descripcion: 'Mejillones con mantequilla clarificada y vino blanco',
    tiempoPrep: 15,
    proteina: ['mariscos'],
  },
  {
    id: 'pro-034',
    nombre: 'Mejillón Al Chef',
    categoria: 'proteinas',
    subcategoria: 'mejillones',
    precio: 240,
    descripcion: 'Mejillones con una salsa picante a base de peperoncino y salsa bechamel',
    tiempoPrep: 15,
    proteina: ['mariscos'],
    picante: true,
  },

  // ENTRADAS - SOPAS
  {
    id: 'ent-020',
    nombre: 'Sopa Minestrón',
    nombreItalia: 'Minestrone',
    categoria: 'entradas',
    subcategoria: 'sopas',
    precio: 140,
    descripcion: 'Sopa de verduras al mero estilo italiano con apio, zanahoria, papa y tomate',
    tiempoPrep: 12,
  },
  {
    id: 'ent-021',
    nombre: 'Crema de Brócoli',
    categoria: 'entradas',
    subcategoria: 'sopas',
    precio: 140,
    descripcion: 'Clásica crema de brócoli con un toque de parmesano',
    tiempoPrep: 12,
  },
  {
    id: 'ent-022',
    nombre: 'Clam Chowder',
    categoria: 'entradas',
    subcategoria: 'sopas',
    precio: 190,
    descripcion: 'Clásica crema de almeja',
    tiempoPrep: 15,
    proteina: ['mariscos'],
  },

  // ENTRADAS - ENSALADAS
  {
    id: 'ent-023',
    nombre: 'Ensalada César',
    nombreItalia: 'Insalata Cesare',
    categoria: 'entradas',
    subcategoria: 'ensaladas',
    precio: 155,
    descripcion: 'Preparada en mesa por nuestro capitán',
    tiempoPrep: 10,
  },
  {
    id: 'ent-024',
    nombre: 'Ensalada Caprese',
    nombreItalia: 'Insalata Caprese',
    categoria: 'entradas',
    subcategoria: 'ensaladas',
    precio: 160,
    descripcion: 'Queso Mozzarella fresco, jitomate y albahaca',
    tiempoPrep: 8,
  },
  {
    id: 'ent-025',
    nombre: 'Ensalada Bella-Lato',
    categoria: 'entradas',
    subcategoria: 'ensaladas',
    precio: 170,
    descripcion: 'Mezcla de lechugas con nuez acaramelada, prosciutto y helado de hierba buena',
    tiempoPrep: 10,
    proteina: ['cerdo'],
  },
  {
    id: 'ent-026',
    nombre: 'Ensalada Di Mare',
    nombreItalia: 'Insalata di Mare',
    categoria: 'entradas',
    subcategoria: 'ensaladas',
    precio: 240,
    descripcion: 'Mezcla de mariscos, camarón, pulpo, mejillón y calamar con un toque de aceite de oliva y perejil',
    tiempoPrep: 15,
    proteina: ['mariscos'],
  },
  {
    id: 'ent-027',
    nombre: 'Ensalada Caligula',
    categoria: 'entradas',
    subcategoria: 'ensaladas',
    precio: 280,
    descripcion: 'Mezcla de lechugas con vinagreta de frutos rojos y queso burrata',
    tiempoPrep: 10,
  },

  // PIZZAS
  {
    id: 'piz-001',
    nombre: 'Pizza Margarita',
    nombreItalia: 'Pizza Margherita',
    categoria: 'pizzas',
    precio: 160,
    descripcion: 'Queso Mozzarella con albahaca y jitomate',
    tiempoPrep: 18,
  },
  {
    id: 'piz-002',
    nombre: 'Pizza 4 Quesos',
    nombreItalia: 'Pizza Quattro Formaggi',
    categoria: 'pizzas',
    precio: 180,
    descripcion: 'Es nuestra Mezcla de 4 quesos de la casa',
    tiempoPrep: 18,
  },
  {
    id: 'piz-003',
    nombre: 'Pizza Pepperoni',
    categoria: 'pizzas',
    precio: 180,
    descripcion: 'Pepperoni y cebolla morada',
    tiempoPrep: 18,
    proteina: ['cerdo'],
  },
  {
    id: 'piz-004',
    nombre: 'Pizza Especial de la Casa',
    categoria: 'pizzas',
    precio: 199,
    descripcion: 'Aceituna negra, cebolla morada, alcaparra y salchicha italiana con un toque de jalapeño',
    tiempoPrep: 20,
    proteina: ['cerdo'],
    picante: true,
    destacado: true,
  },
  {
    id: 'piz-005',
    nombre: 'Pizza Prosciutto',
    categoria: 'pizzas',
    precio: 225,
    descripcion: 'Láminas de prosciutto con arúgula fresca',
    tiempoPrep: 18,
    proteina: ['cerdo'],
    destacado: true,
  },
  {
    id: 'piz-006',
    nombre: 'Pizza Diávolo',
    categoria: 'pizzas',
    precio: 250,
    descripcion: 'Mezcla de salsa arrabiata con salsa bechamel con camarones y espárragos',
    tiempoPrep: 20,
    proteina: ['mariscos'],
    picante: true,
  },
  {
    id: 'piz-007',
    nombre: 'Pizza Pulpo del Pratto',
    categoria: 'pizzas',
    precio: 250,
    descripcion: 'Mezcla de Pulpo, camarón y marlín ahumado con serrano y cebolla morada',
    tiempoPrep: 20,
    proteina: ['mariscos'],
    picante: true,
  },
  {
    id: 'piz-008',
    nombre: 'Pizza Venecia',
    categoria: 'pizzas',
    precio: 250,
    descripcion: 'Hongo Portobello con queso de cabra cenizo, cebolla y salchicha italiana',
    tiempoPrep: 20,
    proteina: ['cerdo'],
  },

  // PASTAS TRADICIONALES
  {
    id: 'pas-001',
    nombre: 'Pasta al Burro',
    categoria: 'pastas',
    subcategoria: 'tradicionales',
    precio: 120,
    descripcion: 'Mantequilla y parmesano',
    tiempoPrep: 15,
  },
  {
    id: 'pas-002',
    nombre: 'Pasta Pomodoro',
    categoria: 'pastas',
    subcategoria: 'tradicionales',
    precio: 140,
    descripcion: 'Clásica Pomodoro',
    tiempoPrep: 15,
  },
  {
    id: 'pas-003',
    nombre: 'Pasta Alfredo',
    categoria: 'pastas',
    subcategoria: 'tradicionales',
    precio: 150,
    descripcion: 'Salsa 3 Quesos',
    tiempoPrep: 18,
  },
  {
    id: 'pas-004',
    nombre: 'Pasta Boloñesa',
    nombreItalia: 'Pasta alla Bolognese',
    categoria: 'pastas',
    subcategoria: 'tradicionales',
    precio: 155,
    descripcion: 'Clásica Pasta con salsa boloñesa',
    tiempoPrep: 18,
    proteina: ['res'],
  },
  {
    id: 'pas-005',
    nombre: 'Pasta Arrabiata',
    nombreItalia: "Pasta all'Arrabbiata",
    categoria: 'pastas',
    subcategoria: 'tradicionales',
    precio: 155,
    descripcion: 'Pomodoro con un toque de picante y pimiento morrón',
    tiempoPrep: 18,
    picante: true,
  },
  {
    id: 'pas-006',
    nombre: 'Pasta Pesto',
    nombreItalia: 'Pasta al Pesto',
    categoria: 'pastas',
    subcategoria: 'tradicionales',
    precio: 155,
    descripcion: 'Salsa a base de piñón, albahaca, aceite de oliva y parmesano',
    tiempoPrep: 15,
    destacado: true,
  },
  {
    id: 'pas-007',
    nombre: 'Pasta Carbonara',
    nombreItalia: 'Pasta alla Carbonara',
    categoria: 'pastas',
    subcategoria: 'tradicionales',
    precio: 155,
    descripcion: 'A base de huevo, tocino y parmesano',
    tiempoPrep: 18,
    proteina: ['cerdo'],
    destacado: true,
  },
  {
    id: 'pas-008',
    nombre: 'Pasta Diávolo',
    categoria: 'pastas',
    subcategoria: 'tradicionales',
    precio: 160,
    descripcion: 'Salsa a base de bechamel y arrabiata (cremosa picante)',
    tiempoPrep: 18,
    picante: true,
  },

  // BELLARYA SPECIALE
  {
    id: 'pas-009',
    nombre: 'Peperoncino Verde',
    categoria: 'pastas',
    subcategoria: 'speciale',
    precio: 199,
    descripcion: 'Pasta con base de chile poblano y un toque de parmesano',
    tiempoPrep: 20,
  },
  {
    id: 'pas-010',
    nombre: 'Pasta Rosa',
    categoria: 'pastas',
    subcategoria: 'speciale',
    precio: 270,
    descripcion: 'Salsa cremosa a base de salmón con una combinación de jitomates de la casa',
    tiempoPrep: 22,
    proteina: ['pescado'],
  },
  {
    id: 'pas-011',
    nombre: 'Frutti Di Mare',
    categoria: 'pastas',
    subcategoria: 'speciale',
    precio: 280,
    descripcion: 'Mezcla de mariscos con un fondo de mariscos',
    tiempoPrep: 25,
    proteina: ['mariscos'],
  },
  {
    id: 'pas-012',
    nombre: 'Grana Bellarya',
    categoria: 'pastas',
    subcategoria: 'speciale',
    precio: 360,
    descripcion: 'Preparada en mesa - Pasta fettuccini con una salsa cremosa de la casa con aceite de trufa y trufa en conserva',
    tiempoPrep: 20,
  },
  {
    id: 'pas-013',
    nombre: 'Fusilli Lágrimas de Pratto',
    categoria: 'pastas',
    subcategoria: 'speciale',
    precio: 360,
    descripcion: 'Salsa de 4 quesos con jitomates cherry frescos',
    tiempoPrep: 20,
  },

  // POSTRES
  {
    id: 'pos-001',
    nombre: 'Cheese Cake',
    categoria: 'postres',
    precio: 150,
    descripcion: 'Delicioso pastel de queso estilo New York',
    tiempoPrep: 5,
  },
  {
    id: 'pos-002',
    nombre: 'Coliseo de Chocolate',
    categoria: 'postres',
    precio: 160,
    descripcion: 'Postre de chocolate con capas decadentes',
    tiempoPrep: 5,
  },
  {
    id: 'pos-003',
    nombre: 'Tiramisú',
    categoria: 'postres',
    precio: 160,
    descripcion: 'Clásico postre italiano con café, mascarpone y cacao',
    tiempoPrep: 5,
  },
  {
    id: 'pos-004',
    nombre: 'Brownie',
    categoria: 'postres',
    precio: 160,
    descripcion: 'Brownie de chocolate servido caliente',
    tiempoPrep: 8,
  },
  {
    id: 'pos-005',
    nombre: 'Helado',
    categoria: 'postres',
    precio: 60,
    descripcion: 'Helado artesanal (sabores variados)',
    tiempoPrep: 3,
  },

  // BEBIDAS - CERVEZA
  {
    id: 'beb-001',
    nombre: 'Corona Clara/Oscura',
    categoria: 'bebidas',
    subcategoria: 'cerveza',
    precio: 50,
    descripcion: 'Cerveza mexicana clásica',
  },
  {
    id: 'beb-002',
    nombre: 'Victoria',
    categoria: 'bebidas',
    subcategoria: 'cerveza',
    precio: 50,
    descripcion: 'Cerveza mexicana',
  },
  {
    id: 'beb-003',
    nombre: 'Pacífico',
    categoria: 'bebidas',
    subcategoria: 'cerveza',
    precio: 50,
    descripcion: 'Cerveza clara mexicana',
  },
  {
    id: 'beb-004',
    nombre: 'Modelo Especial',
    categoria: 'bebidas',
    subcategoria: 'cerveza',
    precio: 60,
    descripcion: 'Cerveza mexicana premium',
  },
  {
    id: 'beb-005',
    nombre: 'Negra Modelo',
    categoria: 'bebidas',
    subcategoria: 'cerveza',
    precio: 60,
    descripcion: 'Cerveza oscura mexicana',
  },
  {
    id: 'beb-006',
    nombre: 'Stella Artois',
    categoria: 'bebidas',
    subcategoria: 'cerveza',
    precio: 65,
    descripcion: 'Cerveza belga premium',
  },
  {
    id: 'beb-007',
    nombre: 'Miller',
    categoria: 'bebidas',
    subcategoria: 'cerveza',
    precio: 65,
    descripcion: 'Cerveza americana',
  },
  {
    id: 'beb-008',
    nombre: 'Heineken',
    categoria: 'bebidas',
    subcategoria: 'cerveza',
    precio: 65,
    descripcion: 'Cerveza holandesa premium',
  },
  {
    id: 'beb-009',
    nombre: 'Amstel Ultra',
    categoria: 'bebidas',
    subcategoria: 'cerveza',
    precio: 75,
    descripcion: 'Cerveza ligera premium',
  },
  {
    id: 'beb-010',
    nombre: 'Tecate',
    categoria: 'bebidas',
    subcategoria: 'cerveza',
    precio: 40,
    descripcion: 'Cerveza mexicana clásica',
  },
  {
    id: 'beb-011',
    nombre: 'Tecate Light',
    categoria: 'bebidas',
    subcategoria: 'cerveza',
    precio: 40,
    descripcion: 'Cerveza mexicana ligera',
  },
  {
    id: 'beb-012',
    nombre: 'XX Lager',
    categoria: 'bebidas',
    subcategoria: 'cerveza',
    precio: 40,
    descripcion: 'Cerveza mexicana lager',
  },
  {
    id: 'beb-013',
    nombre: 'XX Ámbar',
    categoria: 'bebidas',
    subcategoria: 'cerveza',
    precio: 55,
    descripcion: 'Cerveza mexicana ámbar',
  },
  {
    id: 'beb-014',
    nombre: 'Bohemia Clara/Oscura',
    categoria: 'bebidas',
    subcategoria: 'cerveza',
    precio: 60,
    descripcion: 'Cerveza mexicana artesanal',
  },
  {
    id: 'beb-015',
    nombre: 'Bohemia Kristal',
    categoria: 'bebidas',
    subcategoria: 'cerveza',
    precio: 60,
    descripcion: 'Cerveza mexicana artesanal clara',
  },
  {
    id: 'beb-016',
    nombre: 'Strongbow Preparado',
    categoria: 'bebidas',
    subcategoria: 'cerveza',
    precio: 60,
    descripcion: 'Sidra preparada',
  },
  {
    id: 'beb-017',
    nombre: 'Michelada',
    categoria: 'bebidas',
    subcategoria: 'cerveza',
    precio: 35,
    descripcion: 'Preparado clásico mexicano',
  },

  // BEBIDAS - CERVEZA ARTESANAL
  {
    id: 'beb-018',
    nombre: 'Cañita',
    categoria: 'bebidas',
    subcategoria: 'cerveza artesanal',
    precio: 90,
    descripcion: 'Cerveza artesanal local',
  },
  {
    id: 'beb-019',
    nombre: 'California Ale',
    categoria: 'bebidas',
    subcategoria: 'cerveza artesanal',
    precio: 90,
    descripcion: 'Cerveza artesanal estilo californiano',
  },
  {
    id: 'beb-020',
    nombre: 'Pale Ale',
    categoria: 'bebidas',
    subcategoria: 'cerveza artesanal',
    precio: 90,
    descripcion: 'Cerveza artesanal pale ale',
  },
  {
    id: 'beb-021',
    nombre: 'Hazy Pale Ale',
    categoria: 'bebidas',
    subcategoria: 'cerveza artesanal',
    precio: 90,
    descripcion: 'Cerveza artesanal turbia',
  },
  {
    id: 'beb-022',
    nombre: 'Stout',
    categoria: 'bebidas',
    subcategoria: 'cerveza artesanal',
    precio: 90,
    descripcion: 'Cerveza artesanal oscura',
  },
  {
    id: 'beb-023',
    nombre: 'IPA Ippolita',
    categoria: 'bebidas',
    subcategoria: 'cerveza artesanal',
    precio: 90,
    descripcion: 'India Pale Ale artesanal',
  },
  {
    id: 'beb-024',
    nombre: 'Sake Ale',
    categoria: 'bebidas',
    subcategoria: 'cerveza artesanal',
    precio: 90,
    descripcion: 'Cerveza artesanal fusión',
  },
  {
    id: 'beb-025',
    nombre: 'Neipolita',
    categoria: 'bebidas',
    subcategoria: 'cerveza artesanal',
    precio: 90,
    descripcion: 'Cerveza artesanal neipa',
  },

  // BEBIDAS - REFRESCOS
  {
    id: 'beb-026',
    nombre: 'Coca Cola',
    categoria: 'bebidas',
    subcategoria: 'refresco',
    precio: 38,
    descripcion: 'Refresco de cola',
  },
  {
    id: 'beb-027',
    nombre: 'Coca Cola Light',
    categoria: 'bebidas',
    subcategoria: 'refresco',
    precio: 38,
    descripcion: 'Refresco de cola light',
  },
  {
    id: 'beb-028',
    nombre: 'Coca Zero',
    categoria: 'bebidas',
    subcategoria: 'refresco',
    precio: 38,
    descripcion: 'Refresco de cola sin azúcar',
  },
  {
    id: 'beb-029',
    nombre: 'Sprite',
    categoria: 'bebidas',
    subcategoria: 'refresco',
    precio: 38,
    descripcion: 'Refresco de lima-limón',
  },
  {
    id: 'beb-030',
    nombre: 'Fanta',
    categoria: 'bebidas',
    subcategoria: 'refresco',
    precio: 38,
    descripcion: 'Refresco de naranja',
  },
  {
    id: 'beb-031',
    nombre: 'Fresca',
    categoria: 'bebidas',
    subcategoria: 'refresco',
    precio: 38,
    descripcion: 'Refresco de toronja',
  },
  {
    id: 'beb-032',
    nombre: 'Agua Mineral Peñafiel',
    categoria: 'bebidas',
    subcategoria: 'refresco',
    precio: 38,
    descripcion: 'Agua con gas',
  },
  {
    id: 'beb-033',
    nombre: 'Perrier',
    categoria: 'bebidas',
    subcategoria: 'refresco',
    precio: 65,
    descripcion: 'Agua con gas premium',
  },
  {
    id: 'beb-034',
    nombre: 'Agua de Piedra Grande',
    categoria: 'bebidas',
    subcategoria: 'refresco',
    precio: 90,
    descripcion: 'Agua natural premium',
  },
  {
    id: 'beb-035',
    nombre: 'Limonada',
    categoria: 'bebidas',
    subcategoria: 'refresco',
    precio: 50,
    descripcion: 'Limonada natural de la casa',
  },
  {
    id: 'beb-036',
    nombre: 'Naranjada',
    categoria: 'bebidas',
    subcategoria: 'refresco',
    precio: 50,
    descripcion: 'Naranjada natural de la casa',
  },

  // BEBIDAS - CAFÉ
  {
    id: 'beb-037',
    nombre: 'Americano',
    categoria: 'bebidas',
    subcategoria: 'café',
    precio: 45,
    descripcion: 'Café americano',
    tiempoPrep: 5,
  },
  {
    id: 'beb-038',
    nombre: 'Espresso',
    categoria: 'bebidas',
    subcategoria: 'café',
    precio: 50,
    descripcion: 'Café espresso italiano',
    tiempoPrep: 3,
  },
  {
    id: 'beb-039',
    nombre: 'Espresso Doble',
    categoria: 'bebidas',
    subcategoria: 'café',
    precio: 80,
    descripcion: 'Doble shot de espresso',
    tiempoPrep: 3,
  },
  {
    id: 'beb-040',
    nombre: 'Capuchino',
    categoria: 'bebidas',
    subcategoria: 'café',
    precio: 85,
    descripcion: 'Café capuchino italiano',
    tiempoPrep: 5,
  },
  {
    id: 'beb-041',
    nombre: 'Chaí',
    categoria: 'bebidas',
    subcategoria: 'café',
    precio: 85,
    descripcion: 'Té chai con leche',
    tiempoPrep: 5,
  },
  {
    id: 'beb-042',
    nombre: 'Affogato',
    categoria: 'bebidas',
    subcategoria: 'café',
    precio: 100,
    descripcion: 'Helado de vainilla con espresso caliente',
    tiempoPrep: 5,
  },
  {
    id: 'beb-043',
    nombre: 'Carajillo',
    categoria: 'bebidas',
    subcategoria: 'café',
    precio: 180,
    descripcion: 'Café con licor',
    tiempoPrep: 5,
  },
  {
    id: 'beb-044',
    nombre: 'Canija',
    categoria: 'bebidas',
    subcategoria: 'café',
    precio: 180,
    descripcion: 'Café especial de la casa con licor',
    tiempoPrep: 5,
  },
  {
    id: 'beb-045',
    nombre: 'Chocolate Caliente',
    categoria: 'bebidas',
    subcategoria: 'café',
    precio: 80,
    descripcion: 'Chocolate caliente artesanal',
    tiempoPrep: 5,
  },
  {
    id: 'beb-046',
    nombre: 'Frappuccino',
    categoria: 'bebidas',
    subcategoria: 'café',
    precio: 100,
    descripcion: 'Café frío batido',
    tiempoPrep: 5,
  },

  // BEBIDAS - MOCTELERÍA
  {
    id: 'beb-047',
    nombre: 'MARLEN',
    categoria: 'bebidas',
    subcategoria: 'moctelería',
    precio: 90,
    descripcion: 'Maracuyá, Naranja, Limón y Piña',
    tiempoPrep: 5,
  },
  {
    id: 'beb-048',
    nombre: 'JANETT',
    categoria: 'bebidas',
    subcategoria: 'moctelería',
    precio: 90,
    descripcion: 'Fresa, Frutos Rojos, Limón y Jugo de Arándano',
    tiempoPrep: 5,
  },
  {
    id: 'beb-049',
    nombre: 'VIRIDIANA',
    categoria: 'bebidas',
    subcategoria: 'moctelería',
    precio: 90,
    descripcion: 'Lichi, Menta, Hierba Buena y Limón',
    tiempoPrep: 5,
  },

  // BEBIDAS - SODAS ITALIANAS
  {
    id: 'beb-050',
    nombre: 'Mora Azul',
    categoria: 'bebidas',
    subcategoria: 'sodas italianas',
    precio: 75,
    descripcion: '¡Con Perlas Explosivas de Sabor!',
    tiempoPrep: 5,
  },
  {
    id: 'beb-051',
    nombre: 'Manzana Verde',
    categoria: 'bebidas',
    subcategoria: 'sodas italianas',
    precio: 75,
    descripcion: '¡Con Perlas Explosivas de Sabor!',
    tiempoPrep: 5,
  },
  {
    id: 'beb-052',
    nombre: 'Frutos Rojos',
    categoria: 'bebidas',
    subcategoria: 'sodas italianas',
    precio: 75,
    descripcion: '¡Con Perlas Explosivas de Sabor!',
    tiempoPrep: 5,
  },

  // BEBIDAS - COCTELERÍA
  {
    id: 'beb-053',
    nombre: 'COLISEO',
    categoria: 'bebidas',
    subcategoria: 'coctelería',
    precio: 120,
    descripcion: 'Esencia de Cereza, Vino Tinto, Naranja y Fritura de Durazno',
    tiempoPrep: 8,
  },
  {
    id: 'beb-054',
    nombre: 'POMPEYA',
    categoria: 'bebidas',
    subcategoria: 'coctelería',
    precio: 120,
    descripcion: 'Frutos Rojos, Limón, Arándano, Vino tinto, Té de Limón y Menta',
    tiempoPrep: 8,
  },
  {
    id: 'beb-055',
    nombre: 'FLORENCIA',
    categoria: 'bebidas',
    subcategoria: 'coctelería',
    precio: 140,
    descripcion: 'Jugo de Durazno, Vino Blanco, Kiwi, Limón y Licor de Durazno',
    tiempoPrep: 8,
  },
  {
    id: 'beb-056',
    nombre: 'VENUS',
    categoria: 'bebidas',
    subcategoria: 'coctelería',
    precio: 160,
    descripcion: 'Vino Rosado, Ginger, Limón, Esencia de Cereza y Fresa',
    tiempoPrep: 8,
  },
  {
    id: 'beb-057',
    nombre: 'MEDUSA',
    categoria: 'bebidas',
    subcategoria: 'coctelería',
    precio: 120,
    descripcion: 'Té de Bugambilia, Vino Tinto, Limón',
    tiempoPrep: 8,
  },
  {
    id: 'beb-058',
    nombre: 'APEROL SPRITZ',
    categoria: 'bebidas',
    subcategoria: 'coctelería',
    precio: 180,
    descripcion: 'Aperol, Prosecco y Soda',
    tiempoPrep: 5,
  },
  {
    id: 'beb-059',
    nombre: 'SAN GERMAIN SPRITZ',
    categoria: 'bebidas',
    subcategoria: 'coctelería',
    precio: 200,
    descripcion: 'St. Germain, Prosecco y Mineral',
    tiempoPrep: 5,
  },
  {
    id: 'beb-060',
    nombre: 'FANTASÍA EN VENECIA',
    categoria: 'bebidas',
    subcategoria: 'coctelería',
    precio: 140,
    descripcion: 'Vino Tinto, Refresco de Naranja, Tapioca Esencia de Cereza y Limón',
    tiempoPrep: 8,
  },
  {
    id: 'beb-061',
    nombre: 'FORESTA',
    categoria: 'bebidas',
    subcategoria: 'coctelería',
    precio: 160,
    descripcion: 'Prosecco, Mineral, Limón y Kiwi',
    tiempoPrep: 8,
  },
  {
    id: 'beb-062',
    nombre: 'GALILEO GALILEI',
    categoria: 'bebidas',
    subcategoria: 'coctelería',
    precio: 170,
    descripcion: 'Vino Tinto, Té de Limón, Limón y Hpnotiq',
    tiempoPrep: 8,
  },
  {
    id: 'beb-063',
    nombre: 'CALIGULA',
    categoria: 'bebidas',
    subcategoria: 'coctelería',
    precio: 170,
    descripcion: 'Prosecco, Frutos Rojos, Arándanos, Esencia de Cereza y Limón',
    tiempoPrep: 8,
  },
  {
    id: 'beb-064',
    nombre: 'ROMA',
    categoria: 'bebidas',
    subcategoria: 'coctelería',
    precio: 170,
    descripcion: 'Curazao Azul, Toronja, Limón, Piña y Maracuyá',
    tiempoPrep: 8,
  },
  {
    id: 'beb-065',
    nombre: 'CLERICOT',
    categoria: 'bebidas',
    subcategoria: 'coctelería',
    precio: 95,
    descripcion: 'Vino blanco con frutas de temporada',
    tiempoPrep: 5,
  },

  // VINOS BLANCOS
  {
    id: 'beb-066',
    nombre: 'Roccaventosa',
    categoria: 'vinos',
    subcategoria: 'vinos blancos',
    precio: 550,
    descripcion: 'Vino blanco italiano',
  },
  {
    id: 'beb-067',
    nombre: 'Pinot Grigio Terre de Abruzzo',
    categoria: 'vinos',
    subcategoria: 'vinos blancos',
    precio: 140,
    descripcion: 'Pinot Grigio, Italia - Copa',
  },
  {
    id: 'beb-068',
    nombre: 'Monte Xanic Viña Kristel',
    categoria: 'vinos',
    subcategoria: 'vinos blancos',
    precio: 1200,
    descripcion: 'Sauvignon Blanc, México',
  },
  {
    id: 'beb-069',
    nombre: 'LA. Cetto Fumé Blanc',
    categoria: 'vinos',
    subcategoria: 'vinos blancos',
    precio: 520,
    descripcion: 'Sauvignon Blanc, México',
  },
  {
    id: 'beb-070',
    nombre: 'Santo Tomas 1.8.',
    categoria: 'vinos',
    subcategoria: 'vinos blancos',
    precio: 900,
    descripcion: 'Chenin Blanc, Colombard, México',
  },
  {
    id: 'beb-071',
    nombre: 'Pan y Lola',
    categoria: 'vinos',
    subcategoria: 'vinos blancos',
    precio: 1600,
    descripcion: 'Albariño, España',
  },
  {
    id: 'beb-072',
    nombre: 'Porta G Vinho Verde',
    categoria: 'vinos',
    subcategoria: 'vinos blancos',
    precio: 550,
    descripcion: 'Arinto de Brilhacelas, Loureiro, Trajadura, Portugal',
  },
  {
    id: 'beb-073',
    nombre: 'Collevento 921 Prosecco',
    categoria: 'vinos',
    subcategoria: 'vinos blancos',
    precio: 1500,
    descripcion: 'Cuvée, Italia',
  },

  // VINOS ROSADOS
  {
    id: 'beb-074',
    nombre: 'Casa Madero V.',
    categoria: 'vinos',
    subcategoria: 'vinos rosados',
    precio: 900,
    descripcion: 'Shiraz, México',
  },
  {
    id: 'beb-075',
    nombre: 'LA Cetto',
    categoria: 'vinos',
    subcategoria: 'vinos rosados',
    precio: 500,
    descripcion: 'Zinfandel, México',
  },
  {
    id: 'beb-076',
    nombre: 'Roccaventosa',
    categoria: 'vinos',
    subcategoria: 'vinos rosados',
    precio: 750,
    descripcion: 'Montepulciano, Cerasuolo D\'Abruzzo - Copa $180',
  },
  {
    id: 'beb-077',
    nombre: 'Whispering Angel',
    categoria: 'vinos',
    subcategoria: 'vinos rosados',
    precio: 1800,
    descripcion: 'Grenache, Cinsault, Vermentino, Francia',
  },

  // VINOS TINTOS
  {
    id: 'beb-078',
    nombre: 'Santo Tomas Cabernet Sauvignon',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 700,
    descripcion: 'Cabernet Sauvignon, México',
  },
  {
    id: 'beb-079',
    nombre: 'Merlot',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 165,
    descripcion: 'Merlot, México - Copa',
  },
  {
    id: 'beb-080',
    nombre: 'Santo Tomas 31.8',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 1200,
    descripcion: 'Tempranillo, Cabernet Sauvignon, Syrah, México',
  },
  {
    id: 'beb-081',
    nombre: 'Santo Tomas Tempranillo',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 1100,
    descripcion: 'Tempranillo, Cabernet Sauvignon, México',
  },
  {
    id: 'beb-082',
    nombre: 'Monte Xanic Calixa',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 1200,
    descripcion: 'Tempranillo, Cabernet Sauvignon, México',
  },
  {
    id: 'beb-083',
    nombre: 'Monte Xanic Gran Ricardo',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 4500,
    descripcion: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot, Malbec, México',
  },
  {
    id: 'beb-084',
    nombre: 'Casa Madero 3V',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 990,
    descripcion: 'Cabernet Sauvignon, Merlot, Tempranillo, México',
  },
  {
    id: 'beb-085',
    nombre: 'Casa Madero 3V Gran Reserva',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 2300,
    descripcion: 'Cabernet Sauvignon, Shiraz, Cabernet Franc, México',
  },
  {
    id: 'beb-086',
    nombre: 'LA. Cetto Cabernet Sauvignon',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 500,
    descripcion: 'Cabernet Sauvignon, México',
  },
  {
    id: 'beb-087',
    nombre: 'Predator',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 1100,
    descripcion: 'Zinfandel, Estados Unidos',
  },
  {
    id: 'beb-088',
    nombre: 'Caymus',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 5500,
    descripcion: 'Cabernet Sauvignon, Estados Unidos',
  },
  {
    id: 'beb-089',
    nombre: 'The Prisoner',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 3100,
    descripcion: 'Zinfandel, Cabernet Sauvignon, Petit Sirah, Syrah, Charbono, Estados Unidos',
  },
  {
    id: 'beb-090',
    nombre: 'Terraza de los Andes',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 900,
    descripcion: 'Argentina',
  },
  {
    id: 'beb-091',
    nombre: 'Clos de los Siete',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 240,
    descripcion: 'Argentina - Copa',
  },
  {
    id: 'beb-092',
    nombre: 'Pulpo Final',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 2000,
    descripcion: 'Argentina',
  },
  {
    id: 'beb-093',
    nombre: 'Finca Las Moras',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 650,
    descripcion: 'Argentina',
  },
  {
    id: 'beb-094',
    nombre: 'Isla de Lobos',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 500,
    descripcion: 'Argentina',
  },
  {
    id: 'beb-095',
    nombre: 'Tannat',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 750,
    descripcion: 'Tannat, Uruguay',
  },
  {
    id: 'beb-096',
    nombre: 'Emilio Moro',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 1600,
    descripcion: 'Tempranillo, España',
  },
  {
    id: 'beb-097',
    nombre: 'Finca Resalso, Emilio Moro',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 950,
    descripcion: 'Tempranillo, España',
  },
  {
    id: 'beb-098',
    nombre: 'Cal. Y Canto',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 500,
    descripcion: 'Tempranillo, Merlot, Syrah, España',
  },
  {
    id: 'beb-099',
    nombre: 'Matarromera Óinoz',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 1200,
    descripcion: 'Tempranillo, España',
  },
  {
    id: 'beb-100',
    nombre: 'Malavida',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 650,
    descripcion: 'Tempranillo, España',
  },
  {
    id: 'beb-101',
    nombre: 'Porta G.',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 550,
    descripcion: 'Aragonez, Castelao, Portugal',
  },
  {
    id: 'beb-102',
    nombre: 'Roccaventosa Cabernet Sauvignon',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 600,
    descripcion: 'Cabernet Sauvignon, Italia',
  },
  {
    id: 'beb-103',
    nombre: 'Colle Cavalieri Montepulciano D\'Abruzzo',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 850,
    descripcion: 'Montepulciano D\'Abruzzo, Italia - Copa $150',
  },
  {
    id: 'beb-104',
    nombre: 'Calù Nero D\'Avola',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 1000,
    descripcion: 'Nero D\'Avola, Italia - Copa $200',
  },
  {
    id: 'beb-105',
    nombre: 'Ruffino',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 240,
    descripcion: 'Sangiovese, Italia - Copa',
  },
  {
    id: 'beb-106',
    nombre: 'Maria Tinto',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 1000,
    descripcion: 'Blend, México',
  },
  {
    id: 'beb-107',
    nombre: 'Barolo Ravera 2017',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 1600,
    descripcion: 'Abrigo Giovanni, Italia',
  },
  {
    id: 'beb-108',
    nombre: 'Barolo Ravera 2017 Reserva',
    categoria: 'vinos',
    subcategoria: 'vinos tintos',
    precio: 3700,
    descripcion: 'Abrigo Giovanni, Italia - Copa $500',
  },
];
