import { MenuItem } from '@/types/menu';

export const menuItems: MenuItem[] = [
  // ENTRADAS
  {
    id: 'ent-001',
    nombre: 'Bruschetta Clásica',
    nombreItalia: 'Bruschetta Classica',
    categoria: 'entradas',
    precio: 145,
    descripcion: 'Pan tostado con tomate fresco, albahaca, ajo y aceite de oliva extra virgen',
    tiempoPrep: 10,
  },
  {
    id: 'ent-002',
    nombre: 'Carpaccio de Res',
    nombreItalia: 'Carpaccio di Manzo',
    categoria: 'entradas',
    precio: 285,
    descripcion: 'Finas láminas de filete de res con rúcula, parmesano, alcaparras y reducción balsámica',
    tiempoPrep: 12,
    proteina: ['res'],
  },
  {
    id: 'ent-003',
    nombre: 'Calamares Fritos',
    nombreItalia: 'Calamari Fritti',
    categoria: 'entradas',
    precio: 225,
    descripcion: 'Anillos de calamar rebozados, servidos con salsa marinara y limón',
    tiempoPrep: 15,
    proteina: ['mariscos'],
  },
  {
    id: 'ent-004',
    nombre: 'Ensalada Caprese',
    nombreItalia: 'Insalata Caprese',
    categoria: 'entradas',
    precio: 185,
    descripcion: 'Tomate, mozzarella fresca, albahaca, aceite de oliva y reducción balsámica',
    tiempoPrep: 8,
  },
  {
    id: 'ent-005',
    nombre: 'Arancini Siciliani',
    categoria: 'entradas',
    subcategoria: 'especialidad',
    precio: 165,
    descripcion: 'Bolitas de arroz rellenas de ragú de carne, guisantes y mozzarella, empanizadas y fritas',
    tiempoPrep: 18,
  },
  {
    id: 'ent-006',
    nombre: 'Antipasto Misto',
    categoria: 'entradas',
    precio: 295,
    descripcion: 'Selección de embutidos italianos, quesos, aceitunas, pimientos asados y vegetales marinados',
    tiempoPrep: 10,
    proteina: ['cerdo'],
  },

  // PASTAS
  {
    id: 'pas-001',
    nombre: 'Spaghetti Carbonara',
    nombreItalia: 'Spaghetti alla Carbonara',
    categoria: 'pastas',
    precio: 245,
    descripcion: 'Pasta con pancetta, huevo, queso pecorino romano y pimienta negra',
    tiempoPrep: 20,
    proteina: ['cerdo'],
  },
  {
    id: 'pas-002',
    nombre: 'Fettuccine Alfredo',
    categoria: 'pastas',
    precio: 225,
    descripcion: 'Pasta fresca con salsa cremosa de mantequilla y parmesano',
    tiempoPrep: 18,
  },
  {
    id: 'pas-003',
    nombre: 'Penne Arrabiata',
    nombreItalia: 'Penne all\'Arrabbiata',
    categoria: 'pastas',
    precio: 195,
    descripcion: 'Pasta con salsa de tomate picante, ajo, chile y aceite de oliva',
    tiempoPrep: 22,
    picante: true,
  },
  {
    id: 'pas-004',
    nombre: 'Lasagna Bolognesa',
    nombreItalia: 'Lasagne alla Bolognese',
    categoria: 'pastas',
    precio: 275,
    descripcion: 'Capas de pasta con ragú de carne, bechamel y parmesano gratinado',
    tiempoPrep: 35,
    proteina: ['res', 'cerdo'],
  },
  {
    id: 'pas-005',
    nombre: 'Ravioli de Ricotta',
    nombreItalia: 'Ravioli di Ricotta',
    categoria: 'pastas',
    precio: 265,
    descripcion: 'Pasta rellena de ricotta y espinacas con salsa de mantequilla y salvia',
    tiempoPrep: 25,
  },
  {
    id: 'pas-006',
    nombre: 'Linguine ai Frutti di Mare',
    categoria: 'pastas',
    precio: 345,
    descripcion: 'Linguine con camarones, mejillones, almejas y calamares en salsa de tomate y vino blanco',
    tiempoPrep: 28,
    proteina: ['mariscos'],
  },
  {
    id: 'pas-007',
    nombre: 'Gnocchi al Pesto',
    categoria: 'pastas',
    precio: 235,
    descripcion: 'Ñoquis de papa con salsa pesto genovés, piñones y parmesano',
    tiempoPrep: 20,
  },
  {
    id: 'pas-008',
    nombre: 'Tagliatelle al Tartufo',
    categoria: 'pastas',
    precio: 385,
    descripcion: 'Pasta fresca con salsa cremosa de trufa negra, mantequilla y parmesano',
    tiempoPrep: 22,
  },

  // PROTEINAS
  {
    id: 'pro-001',
    nombre: 'Pollo Parmigiana',
    nombreItalia: 'Pollo alla Parmigiana',
    categoria: 'proteinas',
    precio: 295,
    descripcion: 'Pechuga de pollo empanizada con salsa marinara, mozzarella y parmesano gratinado',
    tiempoPrep: 30,
    proteina: ['pollo'],
  },
  {
    id: 'pro-002',
    nombre: 'Ossobuco Milanese',
    nombreItalia: 'Ossobuco alla Milanese',
    categoria: 'proteinas',
    precio: 445,
    descripcion: 'Jarrete de ternera estofado lentamente en vino blanco, vegetales y gremolata',
    tiempoPrep: 45,
    proteina: ['res'],
  },
  {
    id: 'pro-003',
    nombre: 'Salmón a la Plancha',
    nombreItalia: 'Salmone alla Griglia',
    categoria: 'proteinas',
    precio: 385,
    descripcion: 'Filete de salmón con limón, alcaparras y aceite de oliva, acompañado de vegetales asados',
    tiempoPrep: 25,
    proteina: ['pescado'],
  },
  {
    id: 'pro-004',
    nombre: 'Saltimbocca alla Romana',
    categoria: 'proteinas',
    precio: 365,
    descripcion: 'Medallones de ternera con jamón prosciutto y salvia en salsa de vino blanco',
    tiempoPrep: 28,
    proteina: ['res', 'cerdo'],
  },
  {
    id: 'pro-005',
    nombre: 'Branzino al Horno',
    nombreItalia: 'Branzino al Forno',
    categoria: 'proteinas',
    precio: 425,
    descripcion: 'Lubina entera al horno con hierbas mediterráneas, limón y aceite de oliva',
    tiempoPrep: 35,
    proteina: ['pescado'],
  },
  {
    id: 'pro-006',
    nombre: 'Costillas de Cordero',
    nombreItalia: 'Costolette d\'Agnello',
    categoria: 'proteinas',
    precio: 485,
    descripcion: 'Rack de cordero con costra de hierbas y reducción de vino tinto',
    tiempoPrep: 32,
    proteina: ['cordero'],
  },

  // PIZZAS
  {
    id: 'piz-001',
    nombre: 'Pizza Margherita',
    categoria: 'pizzas',
    precio: 185,
    descripcion: 'Salsa de tomate, mozzarella fresca, albahaca y aceite de oliva',
    tiempoPrep: 18,
  },
  {
    id: 'piz-002',
    nombre: 'Pizza Diavola',
    categoria: 'pizzas',
    precio: 225,
    descripcion: 'Salsa de tomate, mozzarella, salami picante y chile',
    tiempoPrep: 18,
    proteina: ['cerdo'],
    picante: true,
  },
  {
    id: 'piz-003',
    nombre: 'Pizza Quattro Formaggi',
    categoria: 'pizzas',
    precio: 245,
    descripcion: 'Mozzarella, gorgonzola, parmesano y fontina',
    tiempoPrep: 20,
  },
  {
    id: 'piz-004',
    nombre: 'Pizza Prosciutto e Funghi',
    categoria: 'pizzas',
    precio: 265,
    descripcion: 'Salsa de tomate, mozzarella, jamón prosciutto y champiñones',
    tiempoPrep: 20,
    proteina: ['cerdo'],
  },
  {
    id: 'piz-005',
    nombre: 'Pizza Capricciosa',
    categoria: 'pizzas',
    precio: 275,
    descripcion: 'Salsa de tomate, mozzarella, jamón, alcachofas, champiñones y aceitunas',
    tiempoPrep: 22,
    proteina: ['cerdo'],
  },
  {
    id: 'piz-006',
    nombre: 'Pizza Marinara',
    categoria: 'pizzas',
    precio: 285,
    descripcion: 'Salsa de tomate, camarones, mejillones, ajo y perejil',
    tiempoPrep: 22,
    proteina: ['mariscos'],
  },

  // BEBIDAS
  {
    id: 'beb-001',
    nombre: 'Agua Mineral',
    categoria: 'bebidas',
    precio: 45,
    descripcion: 'Agua mineral natural o con gas 500ml',
    tiempoPrep: 2,
  },
  {
    id: 'beb-002',
    nombre: 'Limonada Italiana',
    categoria: 'bebidas',
    precio: 65,
    descripcion: 'Limonada fresca preparada con limones italianos',
    tiempoPrep: 5,
  },
  {
    id: 'beb-003',
    nombre: 'Espresso',
    categoria: 'bebidas',
    precio: 55,
    descripcion: 'Café espresso tradicional italiano',
    tiempoPrep: 3,
  },
  {
    id: 'beb-004',
    nombre: 'Cappuccino',
    categoria: 'bebidas',
    precio: 75,
    descripcion: 'Espresso con leche espumada y cacao',
    tiempoPrep: 5,
  },
  {
    id: 'beb-005',
    nombre: 'Vino Tinto Copa',
    categoria: 'bebidas',
    subcategoria: 'vinos',
    precio: 125,
    descripcion: 'Copa de vino tinto de la casa (Chianti o Montepulciano)',
    tiempoPrep: 2,
  },
  {
    id: 'beb-006',
    nombre: 'Vino Blanco Copa',
    categoria: 'bebidas',
    subcategoria: 'vinos',
    precio: 125,
    descripcion: 'Copa de vino blanco de la casa (Pinot Grigio o Verdicchio)',
    tiempoPrep: 2,
  },
  {
    id: 'beb-007',
    nombre: 'Prosecco',
    categoria: 'bebidas',
    subcategoria: 'vinos',
    precio: 145,
    descripcion: 'Copa de vino espumoso italiano',
    tiempoPrep: 2,
  },
  {
    id: 'beb-008',
    nombre: 'Aperol Spritz',
    categoria: 'bebidas',
    subcategoria: 'cocktails',
    precio: 165,
    descripcion: 'Aperol, prosecco, soda y naranja',
    tiempoPrep: 5,
  },

  // POSTRES
  {
    id: 'pos-001',
    nombre: 'Tiramisú',
    categoria: 'postres',
    precio: 145,
    descripcion: 'Bizcochos de champagne con café, mascarpone y cacao',
    tiempoPrep: 8,
  },
  {
    id: 'pos-002',
    nombre: 'Panna Cotta',
    categoria: 'postres',
    precio: 125,
    descripcion: 'Crema cocida italiana con coulis de frutos rojos',
    tiempoPrep: 8,
  },
  {
    id: 'pos-003',
    nombre: 'Cannoli Siciliani',
    categoria: 'postres',
    precio: 135,
    descripcion: 'Tubos de masa frita rellenos de ricotta dulce con chips de chocolate',
    tiempoPrep: 10,
  },
  {
    id: 'pos-004',
    nombre: 'Affogato',
    categoria: 'postres',
    precio: 115,
    descripcion: 'Helado de vainilla cubierto con espresso caliente',
    tiempoPrep: 5,
  },
  {
    id: 'pos-005',
    nombre: 'Gelato Artesanal',
    categoria: 'postres',
    precio: 95,
    descripcion: 'Tres bolas de helado artesanal italiano (sabores variados)',
    tiempoPrep: 5,
  },
  {
    id: 'pos-006',
    nombre: 'Torta de Limón',
    nombreItalia: 'Torta al Limone',
    categoria: 'postres',
    precio: 135,
    descripcion: 'Tarta de limón italiana con merengue suave',
    tiempoPrep: 8,
  },
];

export const categorias = [
  { id: 'entradas', label: 'Entradas', labelEn: 'Appetizers' },
  { id: 'pastas', label: 'Pastas', labelEn: 'Pastas' },
  { id: 'proteinas', label: 'Proteínas', labelEn: 'Proteins' },
  { id: 'pizzas', label: 'Pizzas', labelEn: 'Pizzas' },
  { id: 'bebidas', label: 'Bebidas', labelEn: 'Drinks' },
  { id: 'vinos', label: 'Vinos', labelEn: 'Wines' },
  { id: 'postres', label: 'Postres', labelEn: 'Desserts' },
] as const;

export const proteinasDisponibles = [
  'res',
  'cerdo',
  'pollo',
  'pescado',
  'mariscos',
  'cordero',
] as const;
